### ISSUE TITLE
Welcome to ⏪ Rewinds

### ISSUE THREAD

**Issue by mhaidarhanif** [mhaidarhanif/rewinds#1]
Welcome to ⏪ Rewinds

**Comment by saashqdev** [comment]
I'm upgrading Rewinds to Remix V2. Just checking to see if you've done it already. Cheers, Dave

**Comment by mhaidarhanif** [comment]
@saashqdev Sure, you can still upgrade it by yourself to v2.

Actually I'm thinking to archive Rewinds, since currently I'm building an alternative and new branding for the template kit, not only for Remix.

I've mentioned this on the README: "This template can still be used as is and quite stable, but will not be updated often anymore."

Also because there are so many changes in the past few months.

Including:

- Remix v2
- Potential Vite plugin
- Various configurations
- Performance improvements
- Theming
- etc

**Comment by saashqdev** [comment]
Thanks for the update.

**Comment by scraperbotai** [comment]
date-fns 

<img width="954" alt="Ekran Resmi 2023-11-09 14 12 32" src="https://github.com/mhaidarhanif/rewinds/assets/147194738/3f596fd3-7f49-4ea5-8468-32088b46e13a">

**Comment by saashqdev** [comment]
I forgot to ask. How is your new template coming along?

**Comment by mhaidarhanif** [comment]
@saashqdev You're welcome

The new template is named 🐶 Dogokit: <https://dogokit.allnimal.com>

The first variant is 🐶 Dogokit Remix: <https://github.com/dogokit/dogokit-remix>

It's ready for production

**Comment by saashqdev** [comment]
Nice! I'll check it out...

Update: Perfect stack (for me anyway). Looks great. (excellent name btw.)

**Comment by mhaidarhanif** [comment]
@saashqdev Awesome. Yeah, it relates to my current series of works.
